project:
  type: website
  resources:
    - plots/plotly_cluster.html
    - Milestone_5_task_1.qmd

website:
  title: ""
  sidebar:
    style: "floating"
    search: true
    contents:
      - section: "Exploratory Analysis"
        contents:
          - href: plots/plotly_cluster.html
            text: "Interactive Plot"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: united
    css: styles.css
    toc: true

editor: visual
