project:
  type: website
  resources:
    - plots/plotly_cluster.html
    - Milestone_5_task_1.qmd

website:
  title: "Art Museum Director Semtiments on Diversity, Equity, and Inclusion as seen in Surveys from 2020 and 2022"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: united
    css: styles.css
    toc: true
    toc-location: left

editor: visual
