project:
  type: website
  resources:
    - plots/plotly_cluster.html
    - Milestone_5_task_1.qmd

website:
  title: "Diversity and Equity in Art Museums: Insights from Director Surveys"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: united
    css: styles.css
    toc: true
    toc-location: left


editor: visual
