
# Exploratory Analysis


<!-- <iframe width = "700" height = "500" src="plots/plotly_cluster.html"></iframe> -->

## PCA and Clustering

```{r}
#| echo: false
#| message: false
#| warning: false
load('PCA_Data.RData')
library(plotly)
library(factoextra)

plot_ly(
  data = cluster_data,
  x = ~PC1,
  y = ~PC2,
  type = 'scatter',
  mode = 'markers',
  color = ~factor(kmeans_cluster_k),
  colors = c("#797d97", "#cac7b9","#eeaa46", "#4a2329", "#e15b4f"),
  text = ~paste("ID:", survey_data_2022_pca$id), 
  hoverinfo = 'text',
  marker = list(size = 8, opacity = 1)
) %>%
  layout(
    title = list(
      text = "K-means Clustering on PCA Data",
      x = 0.5,                      
      xanchor = "center"
    ),
    xaxis = list(title = "PC1"),
    yaxis = list(title = "PC2"),
    legend = list(title = list(text = "Cluster"))
  )


```

## Survey Question Loading Plot

```{r}
#| echo: false
#| message: false
#| warning: false
pca_2022 <- prcomp(survey_data_2022_pca, scale = TRUE, center = TRUE)

#pca graph for variables
fviz_pca_var(pca_2022, select.var = list(contrib = 20), col.var = "contrib",
             gradient.cols = c("#eeaa46", "#797d97"), repel = TRUE)
```

## Informed Bar Plots 



```{r}
#| echo: false
#| message: false
#| warning: false

load('bar_graph_data.RData')

library(ggpubr)
library(haven)
library(tidyverse)
library(ggplot2)
library(dplyr)
library(forcats)
library(viridis)

plt1<-ggplot(survey_data_2022_cleaner,aes(x=MUSEUMTYPE,fill=Q5_1))+
  geom_bar()+
  scale_fill_manual(values = c(
     "Extremely Important"  = "#797d97",
     "Very Important"       = "#e15b4f",
     "Somewhat Important"   = "#eeaa46", 
     "Not Too Important"    = "#4a2329",
     "Not At All Important" = "#44424d",
     "No Response" = "#cac7b9"))+
  ylim(0,100) +
  theme_minimal()+labs(fill='',title='Year: 2022', x = '')


plt2<-ggplot(survey_data_2020_cleaner,aes(x=MUSEUMTYPE,fill=Q7_1))+
  geom_bar()+
   scale_fill_manual(values = c(
     "Extremely Important"  = "#797d97",
     "Very Important"       = "#e15b4f",
     "Somewhat Important"   = "#eeaa46", 
     "Not Too Important"    = "#4a2329",
     "Not At All Important" = "#44424d",
     "No Response" = "#cac7b9"))+
  ylim(0,100) +
  theme_minimal()+labs(fill='',title='Year: 2020', x = '')


plt3<-ggarrange(plt2,plt1,ncol = 2, nrow = 1, common.legend = TRUE, legend = 'right')
annotate_figure(plt3, top = text_grob(str_wrap("How important to you is it that your museum currently serves in the following capacity:The museum regularly acquires artwork?",70), 
               color = "black", size = 14))

```

```{r}
#| echo: false
#| message: false
#| warning: false
plt4<-ggplot(survey_data_2022_cleaner,aes(x=MUSEUMTYPE,fill=Q5_2))+
  geom_bar()+
  scale_fill_manual(values = c(
     "Extremely Important"  = "#797d97",
     "Very Important"       = "#e15b4f",
     "Somewhat Important"   = "#eeaa46", 
     "Not Too Important"    = "#4a2329",
     "Not At All Important" = "#44424d",
     "No Response" = "#cac7b9"))+
  ylim(0,100) +
  theme_minimal()+labs(fill='',title='Year: 2022', x = '')


plt5<-ggplot(survey_data_2020_cleaner,aes(x=MUSEUMTYPE,fill=Q7_2))+
  geom_bar()+
   scale_fill_manual(values = c(
     "Extremely Important"  = "#797d97",
     "Very Important"       = "#e15b4f",
     "Somewhat Important"   = "#eeaa46", 
     "Not Too Important"    = "#4a2329",
     "Not At All Important" = "#44424d",
     "No Response" = "#cac7b9"))+ 
  ylim(0,100) +
  theme_minimal()+labs(fill='',title='Year: 2020', x = '')


plt6<-ggarrange(plt5,plt4,ncol = 2, nrow = 1, common.legend = TRUE, legend = 'right')
annotate_figure(plt6, top = text_grob(str_wrap("How important to you is it that your museum currently serves in the following capacity:The museum displays artwork from its permanent collections",70), 
               color = "black", size = 14))

```

```{r}
#| echo: false
#| message: false
#| warning: false
plt7<-ggplot(survey_data_2022_cleaner,aes(x=MUSEUMTYPE,fill=Q6_1))+
  geom_bar()+
  scale_fill_manual(values = c(
     "Extremely Important"  = "#797d97",
     "Very Important"       = "#e15b4f",
     "Somewhat Important"   = "#eeaa46", 
     "Not Too Important"    = "#4a2329",
     "Not At All Important" = "#44424d",
     "No Response" = "#cac7b9"))+
  ylim(0,100) +
  theme_minimal()+labs(fill='',title='Year: 2022', x = '')


plt8<-ggplot(survey_data_2020_cleaner,aes(x=MUSEUMTYPE,fill=Q8_1))+
  geom_bar()+
   scale_fill_manual(values = c(
     "Extremely Important"  = "#797d97",
     "Very Important"       = "#e15b4f",
     "Somewhat Important"   = "#eeaa46", 
     "Not Too Important"    = "#4a2329",
     "Not At All Important" = "#44424d",
     "No Response" = "#cac7b9"))+ #
  ylim(0,100) +
  theme_minimal()+labs(fill='',title='Year: 2020', x = '')


plt9<-ggarrange(plt8,plt7,ncol = 2, nrow = 1, common.legend = TRUE, legend = 'right')
annotate_figure(plt9, top = text_grob(str_wrap("How important to you is it that your museum will serve in the following capacity in five years: The museum regularly acquires artwork?",70), 
               color = "black", size = 14))

```

```{r}
#| echo: false
#| message: false
#| warning: false
plt10<-ggplot(survey_data_2022_cleaner,aes(x=MUSEUMTYPE,fill=Q6_2))+
  geom_bar()+
  scale_fill_manual(values = c(
     "Extremely Important"  = "#797d97",
     "Very Important"       = "#e15b4f",
     "Somewhat Important"   = "#eeaa46", 
     "Not Too Important"    = "#4a2329",
     "Not At All Important" = "#44424d",
     "No Response" = "#cac7b9"))+
  ylim(0,100) +
  theme_minimal()+labs(fill='',title='Year: 2022', x = '')


plt11<-ggplot(survey_data_2020_cleaner,aes(x=MUSEUMTYPE,fill=Q8_2))+
  geom_bar()+
   scale_fill_manual(values = c(
     "Extremely Important"  = "#797d97",
     "Very Important"       = "#e15b4f",
     "Somewhat Important"   = "#eeaa46", 
     "Not Too Important"    = "#4a2329",
     "Not At All Important" = "#44424d",
     "No Response" = "#cac7b9"))+ 
  ylim(0,100) +
  theme_minimal()+labs(fill='',title='Year: 2020', x = '')


plt12<-ggarrange(plt11,plt10,ncol = 2, nrow = 1, common.legend = TRUE, legend = 'right')
annotate_figure(plt12, top = text_grob(str_wrap("How important to you is it that your museum serves in the following capacity in five years:The museum displays artwork from its permanent collections",70), 
               color = "black", size = 14))


```

```{r}
#| echo: false
#| message: false
#| warning: false
plt13<-ggplot(survey_data_2022_cleaner,aes(x=MUSEUMTYPE,fill=Q6_4))+
  geom_bar()+
  scale_fill_manual(values = c(
     "Extremely Important"  = "#797d97",
     "Very Important"       = "#e15b4f",
     "Somewhat Important"   = "#eeaa46", 
     "Not Too Important"    = "#4a2329",
     "Not At All Important" = "#44424d",
     "No Response" = "#cac7b9"))+
  ylim(0,100) +
  theme_minimal()+labs(fill='',title='Year: 2022', x = '')


plt14<-ggplot(survey_data_2020_cleaner,aes(x=MUSEUMTYPE,fill=Q8_4))+
  geom_bar()+
   scale_fill_manual(values = c(
     "Extremely Important"  = "#797d97",
     "Very Important"       = "#e15b4f",
     "Somewhat Important"   = "#eeaa46", 
     "Not Too Important"    = "#4a2329",
     "Not At All Important" = "#44424d",
     "No Response" = "#cac7b9"))+ 
  ylim(0,100) +
  theme_minimal()+labs(fill='',title='Year: 2020', x = '')

plt15<-ggarrange(plt14,plt13,ncol = 2, nrow = 1, common.legend = TRUE, legend = 'right')
annotate_figure(plt15, top = text_grob(str_wrap("How important to you is it that your museum will serve in the following capacity in five years: The museum ensures the conservation of its collections for the long-term future",70), 
               color = "black", size = 14))



```

```{r}
#| echo: false
#| message: false
#| warning: false
plt16<-ggplot(survey_data_2022_cleaner,aes(x=MUSEUMTYPE,fill=Q8_9))+
  geom_bar()+
   scale_fill_manual(values = c(
     "Very High Priority"  = "#7b3294",
     "High Priority"       = "#984ea3",
     "Somewhat High Priority"   = "#a05260", 
     "Neither A High Priority Nor A Low Priority" = "#905d5d",
     "Somewhat Low Priority" = "#984ea3",
     "Low Priority" = 'maroon',
     "Very Low Priority" = "red",
     "No Response" = "grey"))+
    ylim(0,100) +
  theme_minimal()+labs(fill='',title='Year: 2022', x = '')

  # scale_fill_manual(values = c(
  #    "Extremely Important"  = "#797d97",
  #    "Very Important"       = "#e15b4f",
  #    "Somewhat Important"   = "#eeaa46", 
  #    "Not Too Important"    = "#4a2329",
  #    "Not At All Important" = "#44424d",
  #    "No Response" = "#cac7b9"))+

plt17<-ggplot(survey_data_2020_cleaner,aes(x=MUSEUMTYPE,fill=Q10_9))+
  geom_bar()+
   scale_fill_manual(values = c(
     "Very High Priority"  = "#7b3294",
     "High Priority"       = "#984ea3",
     "Somewhat High Priority"   = "#a05260", 
     "Neither A High Priority Nor A Low Priority" = "#905d5d",
     "Somewhat Low Priority" = "#984ea3",
     "Low Priority" = 'maroon',
     "Very Low Priority" = "red",
     "No Response" = "grey"))+
  ylim(0,100) +
  theme_minimal()+labs(fill='',title='Year: 2020', x = '')


#      "Extremely Important"  = "#797d97",
#      "Very Important"       = "#e15b4f",
#      "Somewhat Important"   = "#eeaa46", 
#      "Not Too Important"    = "#4a2329",
#      "Not At All Important" = "#44424d",
#      "No Response" = "#cac7b9"))+ #

plt18<-ggarrange(plt17,plt16,ncol = 2, nrow = 1,common.legend = TRUE, legend='right')
annotate_figure(plt18, top = text_grob(str_c(str_wrap("How much of a priority do you think each of the following equity, diversity, and inclusion strategies are in the art museum sector as a whole?:Increasing the diversity of staff in senior management positions",75),'\n'), 
               color = "black", size = 14))

```

```{r}
#| echo: false
#| message: false
#| warning: false
plt19<-ggplot(survey_data_2022_cleaner,aes(x=MUSEUMTYPE,fill=Q8_11))+
  geom_bar()+scale_fill_manual(values = c(
     "Very High Priority"  = "#7b3294",
     "High Priority"       = "#984ea3",
     "Somewhat High Priority"   = "#a05260", 
     "Neither A High Priority Nor A Low Priority" = "#905d5d",
     "Somewhat Low Priority" = "#984ea3",
     "Low Priority" = 'maroon',
     "Very Low Priority" = "red",
     "No Response" = "grey"))+
  ylim(0,100) +
  theme_minimal()+labs(fill='',title='Year: 2022', x = '')
  # scale_fill_manual(values = c(
  #    # "Extremely Important"  = "#797d97",
  #    # "Very Important"       = "#e15b4f",
  #    # "Somewhat Important"   = "#eeaa46", 
  #    # "Not Too Important"    = "#4a2329",
  #    # "Not At All Important" = "#44424d",
  #    # "No Response" = "#cac7b9"))+

plt20<-ggplot(survey_data_2020_cleaner,aes(x=MUSEUMTYPE,fill=Q10_10))+
  geom_bar()+scale_fill_manual(values = c(
     "Very High Priority"  = "#7b3294",
     "High Priority"       = "#984ea3",
     "Somewhat High Priority"   = "#a05260", 
     "Neither A High Priority Nor A Low Priority" = "#905d5d",
     "Somewhat Low Priority" = "#984ea3",
     "Low Priority" = 'maroon',
     "Very Low Priority" = "red",
     "No Response" = "grey"))+
  ylim(0,100) +
  theme_minimal()+labs(fill='',title='Year: 2020', x = '')


#      "Extremely Important"  = "#797d97",
#      "Very Important"       = "#e15b4f",
#      "Somewhat Important"   = "#eeaa46", 
#      "Not Too Important"    = "#4a2329",
#      "Not At All Important" = "#44424d",
#      "No Response" = "#cac7b9"))+ #


plt21<-ggarrange(plt20,plt19,ncol = 2, nrow = 1,common.legend = TRUE, legend='right')
annotate_figure(plt21, top = text_grob(str_c(str_wrap("How much of a priority do you think each of the following equity, diversity, and inclusion strategies are in the art museum sector as a whole:Increasing the diversity of museum volunteers?",75),'\n'), 
               color = "black", size = 14))

```







